package com.onyshkiv.finance.util;

import java.util.Map;

public class CurrencyMap {
    public static final Map<String, String> CURRENCIES = Map.ofEntries(
            Map.entry("aed", "Emirati Dirham"),
            Map.entry("afn", "Afghan Afghani"),
            Map.entry("all", "Albanian Lek"),
            Map.entry("amd", "Armenian Dram"),
            Map.entry("ang", "Dutch Guilder"),
            Map.entry("aoa", "Angolan Kwanza"),
            Map.entry("ars", "Argentine Peso"),
            Map.entry("ats", "Austrian Schilling"),
            Map.entry("aud", "Australian Dollar"),
            Map.entry("awg", "Aruban or Dutch Guilder"),
            Map.entry("azm", "Azerbaijani Manat"),
            Map.entry("azn", "Azerbaijan Manat"),
            Map.entry("bam", "Bosnian Convertible Mark"),
            Map.entry("bbd", "Barbadian or Bajan Dollar"),
            Map.entry("bdt", "Bangladeshi Taka"),
            Map.entry("bef", "Belgian Franc"),
            Map.entry("bgn", "Bulgarian Lev"),
            Map.entry("bhd", "Bahraini Dinar"),
            Map.entry("bif", "Burundian Franc"),
            Map.entry("bmd", "Bermudian Dollar"),
            Map.entry("bnd", "Bruneian Dollar"),
            Map.entry("bob", "Bolivian Bolíviano"),
            Map.entry("brl", "Brazilian Real"),
            Map.entry("bsd", "Bahamian Dollar"),
            Map.entry("btn", "Bhutanese Ngultrum"),
            Map.entry("bwp", "Botswana Pula"),
            Map.entry("bzd", "Belizean Dollar"),
            Map.entry("cad", "Canadian Dollar"),
            Map.entry("cdf", "Congolese Franc"),
            Map.entry("chf", "Swiss Franc"),
            Map.entry("clp", "Chilean Peso"),
            Map.entry("cnh", "Chinese Yuan Renminbi Offshore"),
            Map.entry("cny", "Chinese Yuan Renminbi"),
            Map.entry("cop", "Colombian Peso"),
            Map.entry("crc", "Costa Rican Colon"),
            Map.entry("cuc", "Cuban Convertible Peso"),
            Map.entry("cup", "Cuban Peso"),
            Map.entry("cve", "Cape Verdean Escudo"),
            Map.entry("cyp", "Cypriot Pound"),
            Map.entry("czk", "Czech Koruna"),
            Map.entry("dem", "German Deutsche Mark"),
            Map.entry("djf", "Djiboutian Franc"),
            Map.entry("dkk", "Danish Krone"),
            Map.entry("dop", "Dominican Peso"),
            Map.entry("dzd", "Algerian Dinar"),
            Map.entry("eek", "Estonian Kroon"),
            Map.entry("egp", "Egyptian Pound"),
            Map.entry("ern", "Eritrean Nakfa"),
            Map.entry("esp", "Spanish Peseta"),
            Map.entry("etb", "Ethiopian Birr"),
            Map.entry("eur", "Euro"),
            Map.entry("fjd", "Fijian Dollar"),
            Map.entry("fkp", "Falkland Island Pound"),
            Map.entry("frf", "French Franc"),
            Map.entry("gbp", "British Pound"),
            Map.entry("gel", "Georgian Lari"),
            Map.entry("ggp", "Guernsey Pound"),
            Map.entry("ghc", "Ghanaian Cedi"),
            Map.entry("ghs", "Ghanaian Cedi"),
            Map.entry("gip", "Gibraltar Pound"),
            Map.entry("gmd", "Gambian Dalasi"),
            Map.entry("gnf", "Guinean Franc"),
            Map.entry("grd", "Greek Drachma"),
            Map.entry("gtq", "Guatemalan Quetzal"),
            Map.entry("gyd", "Guyanese Dollar"),
            Map.entry("hkd", "Hong Kong Dollar"),
            Map.entry("hnl", "Honduran Lempira"),
            Map.entry("hrk", "Croatian Kuna"),
            Map.entry("htg", "Haitian Gourde"),
            Map.entry("huf", "Hungarian Forint"),
            Map.entry("idr", "Indonesian Rupiah"),
            Map.entry("iep", "Irish Pound"),
            Map.entry("ils", "Israeli Shekel"),
            Map.entry("imp", "Isle of Man Pound"),
            Map.entry("inr", "Indian Rupee"),
            Map.entry("iqd", "Iraqi Dinar"),
            Map.entry("irr", "Iranian Rial"),
            Map.entry("isk", "Icelandic Krona"),
            Map.entry("itl", "Italian Lira"),
            Map.entry("jep", "Jersey Pound"),
            Map.entry("jmd", "Jamaican Dollar"),
            Map.entry("jod", "Jordanian Dinar"),
            Map.entry("jpy", "Japanese Yen"),
            Map.entry("kes", "Kenyan Shilling"),
            Map.entry("kgs", "Kyrgyzstani Som"),
            Map.entry("khr", "Cambodian Riel"),
            Map.entry("kmf", "Comorian Franc"),
            Map.entry("kpw", "North Korean Won"),
            Map.entry("krw", "South Korean Won"),
            Map.entry("kwd", "Kuwaiti Dinar"),
            Map.entry("kyd", "Caymanian Dollar"),
            Map.entry("kzt", "Kazakhstani Tenge"),
            Map.entry("lak", "Lao Kip"),
            Map.entry("lbp", "Lebanese Pound"),
            Map.entry("lkr", "Sri Lankan Rupee"),
            Map.entry("lrd", "Liberian Dollar"),
            Map.entry("lsl", "Basotho Loti"),
            Map.entry("ltl", "Lithuanian Litas"),
            Map.entry("lvl", "Latvian Lat"),
            Map.entry("lyd", "Libyan Dinar"),
            Map.entry("mad", "Moroccan Dirham"),
            Map.entry("mdl", "Moldovan Leu"),
            Map.entry("mga", "Malagasy Ariary"),
            Map.entry("mkd", "Macedonian Denar"),
            Map.entry("mmk", "Burmese Kyat"),
            Map.entry("mnt", "Mongolian Tughrik"),
            Map.entry("mop", "Macau Pataca"),
            Map.entry("mru", "Mauritanian Ouguiya"),
            Map.entry("mur", "Mauritian Rupee"),
            Map.entry("mvr", "Maldivian Rufiyaa"),
            Map.entry("mwk", "Malawian Kwacha"),
            Map.entry("mxn", "Mexican Peso"),
            Map.entry("myr", "Malaysian Ringgit"),
            Map.entry("mzn", "Mozambican Metical"),
            Map.entry("nad", "Namibian Dollar"),
            Map.entry("ngn", "Nigerian Naira"),
            Map.entry("nzd", "New Zealand Dollar"),
            Map.entry("omr", "Omani Rial"),
            Map.entry("pab", "Panamanian Balboa"),
            Map.entry("pen", "Peruvian Sol"),
            Map.entry("php", "Philippine Peso"),
            Map.entry("pkr", "Pakistani Rupee"),
            Map.entry("pln", "Polish Zloty"),
            Map.entry("qar", "Qatari Riyal"),
            Map.entry("ron", "Romanian Leu"),
            Map.entry("rsd", "Serbian Dinar"),
            Map.entry("sar", "Saudi Riyal"),
            Map.entry("sek", "Swedish Krona"),
            Map.entry("sgd", "Singapore Dollar"),
            Map.entry("thb", "Thai Baht"),
            Map.entry("try", "Turkish Lira"),
            Map.entry("uah", "Ukrainian Hryvnia"),
            Map.entry("usd", "US Dollar"),
            Map.entry("vnd", "Vietnamese Dong"),
            Map.entry("zar", "South African Rand")
    );
}
